name: CI Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - 'deps/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Dummy test (always passes)
        run: echo "CI is passing – ready for automerge"
